LOG_TYPE(1, invalid_size, (int16_t, received))
LOG_TYPE(2, invalid_magic_number, (uint32_t, received))
LOG_TYPE(3, invalid_crc, (uint32_t, expected), (uint32_t, received))
LOG_TYPE(4, invalid_uid, (uint32_t, received))
LOG_TYPE(5, older_packet, (uint32_t, current), (uint32_t, received))
LOG_TYPE(6, repeated_packet, (uint32_t, packet_num))
LOG_TYPE(7, full_buffer, (uint32_t, packet_num))
LOG_TYPE(8, success, (uint32_t, packet_num))
LOG_TYPE(9, reader_waiting)
LOG_TYPE(10, packet_recovered, (uint32_t, packet), (uint8_t, versions))
LOG_TYPE(11, packet_not_recovered, (uint32_t, packet), (uint8_t, versions))
LOG_TYPE(12, majority_not_found, (uint32_t, packet), (uint8_t, versions))
LOG_TYPE(13, not_enough_packets, (uint32_t, packet), (uint8_t, versions))
LOG_TYPE(14, validated)
LOG_TYPE(15, playing, (uint32_t, packet))
LOG_TYPE(16, repeat_play, (uint32_t, packet))
LOG_TYPE(17, deferred_writing)
